apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/alertmanager
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: alertmanager-config
  targetNamespace: faas
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: alertmanager-config
      namespace: faas
  chart:
    spec:
      chart: alertmanager
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  releaseName: alertmanager
  targetNamespace: faas
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    installNamespace: false
  valuesFrom:
  - kind: ConfigMap
    name: alertmanager-config
    valuesKey: alertmanager.yaml