---
- hosts: all
  gather_facts: yes

  tasks:
  - name: Get username
    command: whoami
    register: whoami

  - name: Set username fact
    set_fact:
      username: "{{ username | default(whoami.stdout) }}"

  - name: Run a host of prerequisite tasks
    include_role:
      name:  provision

  - import_role:
      name: gantsign.golang
    become: yes
    vars:
      golang_version: "1.15.3"
      golang_gopath: "/home/{{ username }}/repos/go"

  - name: Install docker
    include_role:
      name: docker

  - name: Setup docker registry
    include_role:
      name: docker_registry

  - name: Setup minikube
    include_role:
      name: minikube

  - name: Install GOTK
    include_role:
      name: gotk

  - name: Install linkerd2
    include_role:
      name: linkerd