---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: mittwald
  interval: 5m0s
  releaseName: kubernetes-secret-generator
  targetNamespace: faas-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: generated-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: kubernetes-secret-generator
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/generated-secrets
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: generated-secrets