---
# tasks file for gotk
vars_prompt:
- name: github_user
    prompt: What is your github username?
    private: no

- name: github_token
    prompt: What is your github_token?

- name: github_repo
    prompt: What is your github repository?
    private: no

- name: Download and install GitOps Toolkit
  become: yes
  shell: curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

- name: Check prerequisites
  shell: gotk check --pre

- name: Bootstrap gotk
  shell: >
    GITHUB_TOKEN={{ github_token }}
    gotk bootstrap github
    --owner={{ github_user }}
    --repository={{ github_repo }}
    --branch=main
    --path=minikube
    --personal