apiVersion: v2
name: gateway-api
description: A Helm chart to deploy Gateway API
type: application
version: 0.0.2
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.0.2
  repository: file://../common
