apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stolon
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets-generator
      namespace: flux-system
  chart:
    spec:
      chart: stolon
      sourceRef:
        kind: HelmRepository
        name: kvaps
  interval: 5m0s
  releaseName: stolon
  targetNamespace: stolon
  values:
    superuserSecret:
      name: stolon-superuser
    replicationSecret:
      name: stolon-replication