namespaceName: nsq

nsqd:
  podDisruptionBudget:
    name: nsqd-budget
    labels:
      app: nsq
      component: nsqd
    minAvailable: 1

  service:
    name: nsqd
    labels:
      app: nsqd
    spec:
      ports:
      - port: 4150
        targetPort: 4150
        name: tcp
      - port: 4151
        targetPort: 4151
        name: http
    clusterIP: None
    selector:
      app: nsq
      component: nsqd

  statefulSet:
    name: nsqd
    labels:
      app: nsq
      component: nsqd
    replicas: 3
    updateStrategy: RollingUpdate
    spec:
      container:
        image: nsqio/nsq:v1.2.0 
        imagePullPolicy: Always
        requestsCPU: 30m
        requestsMemory: 64Mi
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        volumeMounts:
        - name: datadir
          mountPath: /data
        command:
          - /nsqd
          - -data-path
          - /data
          - -lookupd-tcp-address
          - nsqlookupd-0.nsqlookupd.nsq.svc.cluster.local:4160
          - -lookupd-tcp-address
          - nsqlookupd-1.nsqlookupd.nsq.svc.cluster.local:4160
          - -lookupd-tcp-address
          - nsqlookupd-2.nsqlookupd.nsq.svc.cluster.local:4160
          - -broadcast-address
          - $(HOSTNAME).nsqd
        env:
        - name: HOSTNAME
          fieldPath: metadata.name
        volume:
        - name: datadir
          persistentVolumeClaimName: datadir
        volumeClaimsTemplates:
        - name: datadir
          accessModes:
            - "ReadWriteOnce"
          storageClassName: ssd
          requestsStorage: 1Gi
      terminationGracePeriodSeconds: 5
    

nsqlookupd:
  podDisruptionBudget:
    name: nsqlookupd-budget
    labels:
      app: nsq
      component: nsqlookupd
    minAvailable: 1

  service:
    name: nsqlookupd
    labels:
      app: nsqd
    spec:
      ports:
      - port: 4160
        targetPort: 4160
        name: tcp
      - port: 4161
        targetPort: 4161
        name: http
    publishNotReadyAddresses: true
    clusterIP: None
    selector:
      app: nsq
      component: nsqlookupd

  statefulSet:
    name: nsqlookupd
    labels:
      app: nsq
      component: nsqlookupd
    replicas: 3
    updateStrategy: RollingUpdate
    spec:
      container:
        image: nsqio/nsq:v1.2.0 
        imagePullPolicy: Always
        requestsCPU: 30m
        requestsMemory: 64Mi
        ports:
        - containerPort: 4160
          name: tcp
        - containerPort: 4161
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        command:
          - /nsqlookupd
      terminationGracePeriodSeconds: 5

nsqadmin:
  deployment:
    name: nsqadmin
    replicas: 1
    labels:
      app: nsq
      component: nsqadmin
    container:
      image: nsqio/nsq:v1.2.0
      imagePullPolicy: Always
      requestsCPU: 30m
      requestsMemory: 64Mi
      ports:
      - containerPort: 4170
        name: tcp
      - containerPort: 4171
        name: http
      livenessProbe:
        httpGet:
          path: /ping
          port: http
        initialDelaySeconds: 10
      readinessProbe:
        httpGet:
          path: /ping
          port: http
        initialDelaySeconds: 5
      command:
        - /nsqadmin
        - -lookupd-http-address
        - nsqlookupd-0.nsqlookupd.nsq.svc.cluster.local:4161
        - -lookupd-http-address
        - nsqlookupd-1.nsqlookupd.nsq.svc.cluster.local:4161
        - -lookupd-http-address
        - nsqlookupd-2.nsqlookupd.nsq.svc.cluster.local:4161
    terminationGracePeriodSeconds: 5