---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tugrik
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
      namespace: flux-system
    - name: mongodb
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/tugrik
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: tugrik
  targetNamespace: faas-system