{{- define "common.container.tpl" -}}
name: {{ .name }}
image: "{{ .image.repository }}:{{ .AppVersion }}"
imagePullPolicy: {{ .image.pullPolicy }}
{{- if .ports }}
{{ template "common.ports" .ports }}
{{- end}}
resources:
{{ toYaml .resources | indent 2 }}
{{- end -}}
{{- define "common.container" -}}
{{- /* clear new line so indentation works correctly */ -}}
{{- println "" -}}
{{- include "common.util.merge" (append . "common.container.tpl") | indent 8 -}}
{{- end -}}
