{{- define "common.serviceaccount.tpl" -}}
apiVersion: v1
kind: ServiceAccount
{{ template "common.metadata" . }}
{{- end -}}
{{- define "common.serviceaccount" -}}
{{- template "common.util.merge" (append . "common.serviceaccount.tpl") -}}
{{- end -}}
