apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stolon-replication
  namespace: stolon
spec:
  encryptedData:
    pg_su_password: AgCAX9X0sC8M1EX1KQfyNNU0nmwf6rJwD66pbGgHdJNATFNp36vwR/Um76QzboKd4nKdeAZv8B3E2bpu3ozBs3+zJCcd6h9/yoNuIxEuhYqWthL0VSkSCYEDL09nubu5VJl6DY7qC8BtkDq2FvDEKGwhZ9QRCLLrYhxm/1RcFQqb0Hq6lchog6t5yYRrvXwLjhSowN+aELXp2zidwuEIV1Fr6RLUBgmTGE7QtrLbopAo/Q6bXRCf6HLWMNTpmEO2zm8owFikAq+cr2h2YQEJFGSNCbbw43LJAlMOeNpQBKOj1HDvZCcfOboLDuxXIfIJqoUNsLTH06elMssmGX5V+6690nibnF/pJkFTgQxZqXUCUfdBEpy67wN0OGvX4lAd/vdICCN4wJWAJ+czIzOZxfQfF2SJkLTv55WBQ7qGOeOkxFtdCgIj2fDovee6nP3ULvr0h5pShKTvsEKUobgHFJZAmVMgAWqKO+WkQyCv++ZxWXqW4MkjoLQF0dKGCG6YwUMhglz6KZ6mnVu37S+KTUAHdIN4b0R96AKkqAu2XXZwDkEpczmxY0oKxsQ44HXkS6+tafO86+ujA0IHxOQiTemT7jPxQScCkfIv0GYC60Tn7mgVAKxMRxMZP3FdS5aUD+vDCy7/FjsVz/RQf2T95n6/KmJjYx5HAcaG+Aiz0Hp+wVo0iCcXEeXyaWnZKwMHg2X4P3YnXkHOm8487sZARIiU7362nIqyKjmi/aYMm8ViFih4OCA=
    pg_su_username: AgCE6YjND/W249hzmmqiUabDjFd7BVxaqvA9bb5mDxBs6plJAg4/NaAvdLxGMF9nfNy+G/L+eGE1jAoE7UePAItCU37lN77QPGpWHiipUJN/SC3/ygndS6dw14dLyC7XCB2AfsTdfwO3dTIDP138VbjVTxg1oBCddn07lYtytDrQJHuXzd00rWZMEI6oM1uGwmSnVbagUBJhzmO+sUPk/F4iebVhc9ZlL6Xeh/n/YXZ3/zdivZ+x/kAqz/HW+MwCZXwX9HrbvkmHD4q5CIbrovx988poOAkUg/2p4O0PUsP0PcJqpSKziaTmt5lzPiZduL/EpdcFUgWcq4PNxq1Yb+HWKA+eo0bKvqJ4ItxgdGhENNNRN8o2ksbR2tmeAenAE/6jNq/KTyMofZBpiGaS7bOuz/on7p5GmehMr2FkttagZkndl5nxHIVIps82h78F68l2DUuSBDQKDqnOs5Rqe33Li8HvV629dUVCl7PI0dKlEI00ZESmRbTzWjdpgr/rp/Bz29jMv9hPdBc7OCX7iXIMP/dZqaIJevdfpuM7pIYM1euRPhWK+VBdeABqIIATryW2Ptq2+1/dAQlgmuqneFHXmym5ieVsgjkYd8i/BRfaWWCIbTfiZEZJmB80DQbugrYRoxRILKNiB0R0sNLwIdbVdAYDgsvYRPoeIRi8jv18aCT4zMO4akVyjmmy/nlZyIIZr0z6KOGc7k70
  template:
    metadata:
      creationTimestamp: null
      name: stolon-replication
      namespace: stolon