apiVersion: v2
name: registry
description: A Helm chart for deploying Registry
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.0.2
  repository: file://../common