---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  dependsOn:
    - name: nats-streaming
      namespace: flux-system
    - name: prometheus-operator-dependents
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/gateway-api
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: gateway-api
  targetNamespace: faas-system