---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: idler
  namespace: flux-system
spec:
  dependsOn:
    - name: key-vault-csi
      namespace: flux-system
    - name: gateway-api
      namespace: flux-system
    - name: prometheus-operator
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/idler
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: idler
  targetNamespace: faas-system