apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 5m0s
  releaseName: prometheus-operator
  targetNamespace: faas-system
  values:
    namespaceOverride: faas-system
    alertmanagerSpec:
      alertManagerConfigSelector:
        matchLabels:
          alertmanagerConfig: custom-alerting-rules
    prometheus:
      evaluationInterval: 1s
      ruleSelector:
        matchLabels:
          app: kube-prometheus-stack
          release: prometheus-operator
      serviceMonitorSelector:
        matchLabels:
          release: prometheus-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator-dependents
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/prometheus-operator-dependents
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: prometheus-operator-dependents
  targetNamespace: faas-system