apiVersion: v2
name: execution-tracker-consumer
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.0.2
  repository: file://../common
