deployment:
  name: execution-tracker-consumer
  replicas: 3
  ports:
  - containerPort: 10080
    name: http
  env:
  - name: EXECUTION_TRACKER_DB_PASSWORD
    secretName: execution-tracker-psql-creds
    secretField: password
  image:
    repository: registry.eywa.rekfuki.dev/execution-tracker-consumer
    tag: latest
    pullPolicy: Always
  imagePullSecret: image-pull-secret