apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eywa
  namespace: gotk-system
spec:
  interval: 1m
  url: https://github.com/Rekfuki/eywa/tree/main/charts
  ref:
    branch: main
  ignore: |
  # exclude all
  /*
  # include charts directory
  !/charts/
