---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: gotk-system
spec:
  channel: eywa
  secretRef:
    name: discord-webhook-url
  type: discord

