---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: verbose
  namespace: gotk-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: gotk-system
  providerRef:
    name: discord

