vaultAddress: http://192.168.1.48:8200
vaultRoleName: secrets-loader

loaders:
- name: kube-pull-loader
  namespaces: ["faas", "faas-system", "envoy", "frontend"]
  secrets:
  - kubeName: image-pull-secret
    kubeType: docker-registry
    vaultPath: v1/secret/docker-registry-auth
    fields:
    - vaultKey: docker-server
      kubeKey: docker-server
    - vaultKey: docker-username
      kubeKey: docker-username
    - vaultKey: docker-password
      kubeKey: docker-password
    - vaultKey: docker-email
      kubeKey: docker-email

- name: registry-auth-loader
  namespaces: ["faas-system"]
  secrets:
  - kubeName: docker-registry-creds
    kubeType: Opaque
    vaultPath: v1/secret/docker-registry-auth
    fields:
    - vaultKey: docker-username
      kubeKey: username
    - vaultKey: docker-password
      kubeKey: password