vaultAddress: http://192.168.1.48:8200
vaultRoleName: secrets-loader

loaders:
- name: kube-pull-loader
  namespaces: ["faas", "faas-system", "envoy", "frontend"]
  secrets:
  - kubeName: image-pull-secret
    kubeType: kubernetes.io/dockerconfigjson
    vaultPath: v1/secret/docker-auth-json
    fields:
    - vaultKey: .dockerconfigjson
      kubeKey: .dockerconfigjson

- name: registry-auth-loader
  namespaces: ["faas-system"]
  secrets:
  - kubeName: docker-registry-creds
    kubeType: Opaque
    vaultPath: v1/secret/docker-registry-auth
    fields:
    - vaultKey: docker-username
      kubeKey: user
    - vaultKey: docker-password
      kubeKey: password