apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-prometheus-rules
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/linkerd-prometheus-rules
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: linkerd-prometheus-rules
  targetNamespace: linkerd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m0s
  dependsOn:
    - name: linkerd-prometheus-rules
      namespace: flux-system
    - name: sealed-secrets-dependents
      namespace: flux-system
    - name: cert-manager-dependents
      namespace: flux-system
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
  releaseName: linkerd
  targetNamespace: linkerd
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    installNamespace: false
    prometheus:
      scrapeConfigs:
        - job_name: "gateway"
          scrape_interval: 5s
          dns_sd_configs:
            - names: ['gateway.faas-system']
              port: 8080
              type: A
              refresh_interval: 1s
      alertManagers:
        - scheme: http
          static_configs:
            - targets:
              - "alertmanager.faas-system"
      ruleConfigMapMounts:
        - name: alerting-rules
          subPath: alerting_rules.yml
          configMap: linkerd-prometheus-rules
  valuesFrom:
  - kind: Secret
    name: linkerd-identity-issuer
    valuesKey: ca.crt
    targetPath: global.identityTrustAnchorsPEM