---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m0s
  dependsOn:
    -
      name: sealed-secrets-dependents
      name: cert-manager-dependents
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
  releaseName: linkerd
  targetNamespace: linkerd
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    installNamespace: false
  valuesFrom:
  - kind: Secret
    name: linkerd-identity-issuer
    valuesKey: ca.crt
    targetPath: global.identityTrustAnchorsPEM