---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/envoy-config
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: envoy-config
  targetNamespace: envoy
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy
  namespace: flux-system
spec:
  dependsOn:
    - name: envoy-config
      namespace: flux-system
    - name: gateway-api
      namespace: flux-system
    - name: execution-tracker-api
      namespace: flux-system
    - name: registry
      namespace: flux-system
    - name: tugrik
      namespace: flux-system
    - name: app
      namespace: flux-system
    - name: swagger-ui
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/envoy
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: envoy
  targetNamespace: envoy