---
- name: Work out kubernetes version
  command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
  register: kubernetes_version

- name: Download Kubectl
  become: yes
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version.stdout }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/
    mode: 755
    owner: root
    group: root

- name: Download Minikube
  become: yes
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
    dest: /usr/local/bin/minikube
    mode: 755
    owner: root
    group: root

- name: Stop Minikube if running
  command: minikube delete
  ignore_errors: yes
  become_user: "{{ username }}"

- name: Setup Minikube
  shell: "/usr/local/bin/minikube start --vm-driver=docker --kubernetes-version={{ kubernetes_version.stdout }}"

- name: Download kubeseal
  become: yes
  get_url:
    url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.12.6/kubeseal-linux-amd64"
    dest: /usr/local/bin/kubeseal
    mode: 755
    owner: root
    group: root