
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - faas.eywa.rekfuki.dev
  resources:
  - functions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - faas.eywa.rekfuki.dev
  resources:
  - functions/status
  verbs:
  - get
  - patch
  - update
