---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  encryptedData:
    tls.crt: AgCzDAZN941oqnC45PKggZtKSuvu6EBq0bSpLEdSxXwiFiAU80jWqZ8kFaqKcw1lfE5I2LB0CnMYawzghyuHFMP1JlX5MuOvldR1xtPwTXjXleRsosmKZzr9W+gp/i0YgYeWwv9vJ/3fgDumi4jg1VmF9ljA2qG74X+dAtSok1D6iCdrWslMbAmGNRHRSTunl6FaDPPesmO3YiIi5HwT2vxmYuqMLIADuK7qBPk7JIq3d3/6qJrk+lW6Mk0WTgyAExxyTCnj2z97KOboIcB+p90rpT2xyU/4j+FOHIZ0jqna9dl6XH0VcRpk3jk0ClPTY/gEhKkcGOb+ElCwrr7kNPgs7+kayYpgib0qbkmrolRzfr3FBZMcAmY/p3bi4l8ibNz+Yt/urDp50zUPYbZ906zy/Os5kwjRg+5yBWZYRMQiyCl8Ujl9GJ0rxG7WlXss3N2sjv7cnC/JkeRZ6pHkbJcaDFm3CGoAzO58h+dLFTtzuhJP+SUcIH0yOQGMIUUXKjd734NrQJw683qoDUtppCE14ctD+J12zkkLT+0UvIKlEUiTsBkbEK7B67M+w3XhEQmg1YBo92JVV1yUlujgnXAvtmweQ7ww3HZRLQ/jZehGdbUqPnwWkL/tZgk0GlPHdHRPsDHZ1OZAKaNKU10D445zE2Rt2Q3t1KQ6BMC6dxmKx6WnqOaHL7oeV5AXqBI840p5Mrtym2d4mrJ+bY7Nvo5MzxbLIPBK5dqhBxO5eIcOi9NQuXISe1GW4wQvXrFje+E6iB1sJq4J3ii6ogp7YPVvrRVvZaXEsFhNIX9sgGIOJDdEvaDh/gD7852R3X2gTr/CfE3OohhgdN4gXi7q75uVhpESngv215AaOurydMrc5FtUPXEQMyzLIoXcd5dvPN3T6eDriKwZLGawLsm3jVt8c5vC/HxtcqwiSrSxmXMuKhxFf5jk8vjZeBJJB/chUEhX625cN9GEhSqcJuw9Geu/tWDNzdgLhbr8Lm/nmgLr3wXqExhk8jaaq8y6bnSAMnUzkBjyAYVEluD+/JUSOCTm32udZzLJbZ39vfYIOeiKSvrEkpTsIfdCkfksMvn5Mb0H5jLBamo4ro+kmH66VOaCU3BJzJGR/I7/4r980pnDDG8lYwINfp/RBafZ1/m34xBHVUkOk5+MGsmaTvZCL9YaMKi840OogkkyDoXrP6P66a20kDGeCwzY9xGt+ctnHKo+Hnhz7XGAIe8VX1+yTV56RpPAHGf7zOnHxbRJLEI3lJnQ/8afoyc11oSNtcUYcPN6TPHsuxZlNkVadjn4ueCSsIokBy7SAEN/aTkMfX3xJje3SDwnJuH2HoZqZsk1TThoVU/LWpHX5E1C7J4C2MRa3W+0kimpgGrgmgHl+cElqMXNoqv2BIrCeTnIpfnJIfS3Jsh2GD1XL+Tg9Ii0N0n9QU4GNB8Zse/tW6oqWYuUukDV7gVABmyL0HC5pgtREjJlU2QSs+uLXzW8CAEh58INhaaGDnUh555fE3OSaxzYgzebjA==
    tls.key: AgBH1JSagsEh5Z09T20eYqGm+jYJ8p34hIBZYFDe5wQY+xYNKFaCG/QQX1dLhz2Hf2JzuIyLiGveDaS3+q1EKl2X1FeAr8TE7ojD1/qAf96BjvZQ3p4mAzFer5/M14/wzgr0KFcsbdqZHog/dO8Sp5awKRSYLJbwQu2jmwR8GnfSghLXRBQhAJLVPGy+vYf0/kXnjY9fxU8LqUsVBS14W5iV9beiq2eD6a6lPnnBOuypNGfoTz/5L6ZKQz2CK0qeD6MGVPE0CnPmxnMDFnpIkqDqMwCYbX3vAYufVtC1TC4rZVyc+wnmN9164POlu5+MLSHnaVoCmaO6WlXN94jKAoFS/0Kh0M15Go0yNaA5kKfiKxqbMKAbROJp85KPkfg1rnXHgE2vbSH1IuLyai+Krxsnri5nFG51Xef29Pb6Du79o3XsDBXnj/p9Ifkyk5wLmLvaLOlMQmFEWPoAJOIKriUdORhYb2eL7bNtIgjZFYNQGEzI/vatPLiv0YwB5g/DGqfDfqHmOcK6YswXRkUbzWAebaLjlp5IiEB5G+uwSh0UtfGgMR58LYtqz0Mxt9ujYjYgEIT54baQiqnLeo0gQjszhdwn1//8yhGuctxeuUI0t1UQtnj/SX9mJBp6tMFEn//Jw2ApQMuMRfmTt8+bEVzKk6KKjIRs8nXFZMhHC/9HZ4GU9SQxs8pKZneHbXjs/HKTjgTJBgnEBeSr8CPCsbEUiU1MhYyc/w9m5mp3QuIFnUZEjkzG09ZSGI6JmPzLX7Vb76BkyzQk+3W5pBNBDNQ+kV64AQ3/6nv0LiCki2aYdMpxDCsk9BmOkDztt54yjHiH/5e5OoNgU8Kf1fAOP3cFTiqBXeBgIxBM4qUXH6trj8WRuToISPUcz8BZqutG6V1SVlQXacyrHE8dXJ228W4qRF7rtNlq0/oZw6ht2y6My1r6WGCGIxO+i8vwtVvAYdnQjNwmNbFcMniSZvX6v6dFcNlB0+4XG+PfpqFsm3bnkxMrpg==
  template:
    metadata:
      name: linkerd-trust-anchor
      namespace: linkerd
    type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: linkerd
data:
  values.yaml: |-
    identinty:
      issuer: 
        scheme: "kubernetes.io/tls"
    installNamespace: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m0s
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
  releaseName: linkerd
  targetNamespace: linkerd
  valuesFrom:
  - kind: Secret
    name: linkerd-identity-issuer
    valuesKey: ca.crt
    targetPath: global.identityTrustAnchorsPEM
  - kind: ConfigMap
    name: linkerd-config