---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  encryptedData:
    tls.crt: AgAILk24EarvUFkWnOHnToR4Avk0Ggv0xRTPQfpzTG/60oelPqzBt+c8Hj9kd7WRjWrIy6TFQhIBemOaXeKeZ41Et8Mhw0l0LknXA0xS5aXOX8udfs88G4/02fGXUFWHHrLUBaRuVWhTTsIGhL1FLKDtNi/1qyb8v3zbYex4+X4I/LMk+cBhYZJPl5QXFD1wam3tLygfeeLZ7XpG0sEXgZgyusSyahoKPbJyzA9v+UPwjMVtXKmCEXM8ECQQLCVNL3gVwAXBG2ghYudRTCrK1ah3FXdAqsLk+7X9WBpTSeWJrzfVRE+wIXS93PcV4EPLArQU3TGdwsPK99NLBADUIM0jCpkmORITFx84uxlz9hKJ9oSiABrFTwyo45WfHCWyOR7N4PiYdEnS1gLnUDXmYbZE74lAVqWXKKgFNfyN1zItNPVm13wtHlbwPJRHD5TxmNmbO70FdxA+17P7zGcCez+E87jGx4AZ/mCdo9obDnGD7w4HYYtnuqUAcdHZli8+/vfAeQQ6VbjS6miZyIjNA4oP4+1/+HyZnAQIdcs6X+N4t0746TnAfsk+Fce0zfuWKIhLrLW9B3jdkY78Wd1vs4hjjEjWHUK/NxkvKFX/5l8AfJYpUVjp2v/7jintKrODjZTtjfrzlMLpGGF+sU0LNrSJjb6NyYyauvAZoA5J+N44evIXmtIU4gDgsF7FDQL5GPVy3x1M6mGsxFYI3zhAvb6yEZ6Mq6GcveBjIMWTTe4NGaQ/URw81f2E4FAfUh3sXdPqzE2poxnq85ug/Lv+9Fe7P0XvGUDWf0ZTz6ok4Q/Ul8Wk2blNkg8TFI0WAMCDXp69gRB03Jvp0VI0Gxyz5/8GuvHha/rTxeyOyKUrcvrDBFxC1s15Xley38qPFkrrtFck6JjoNPlYigNEJnmVBh/b4Sqa0WYBX/jHh7NdOct0bR/xqIB5J8UGBofNhEty8Yn5BZnuQ05fNqnZkiPhgKOpMV6r7+38cJ9ujpOkXBLI8yIHauVBqjfMTbGoVlas+mb0cMQJFumPOIxq689zmmPi4No998nAFpQCqzXE56WxcIq81U/9yFv+AiAepF/+uiKgO0tcfdBow6i2An6xdh7UYeqP1+d64tYiHnXV3hO2DCCiAQs2Eowi/7iV6LaAXNogmJmTuF3iJpBRu1hbsjDsx0eXZWaQ//watkqF+dw00zriCHdJ8FicXi63Npg6hhdFyMMne6fhgRT9latzB4eEaJCZEoiLrqMA1YhpmD4Hj+njdRBU8fT4gFYVkrxdS2g0mqJAfv+Q1SI+XpB4EBW9DymHkWlgy9i+mvVoO3H5GfwWhtm+rl5o2rHE5qm/f5mdVbkfeYzcDym71LraWpFK/4VDBGQBNMftu+VK02RejKwfJjqwLUWBDmY73L1hby+rBTe/oiD58sXPWBjkrCLAkeDW6RoDnPgwR+wLxkzA+UJkU7Esnj21hV3gVxI6/zdqPVI1aMFas0GEW3sryB3bka0aZebRmQg9XxlU/4sz1hy3PQ==
    tls.key: AgCtm8UjBeFuDyKl2y7O/8QXkeGGamjIHmz5yaAjVLOf7psvFm5BRfrz4sADI4nrAdElHUDRh4wT0cncg2a4hiKIaC7Gj+CrmaqL6W14oibptdUt3WlXquhFpbI5vqkyznpBSOCrKulj7o1vJI8+SLqP1em723pLx7Qs4IztmLd54iB+5rNor5bHAqYJzx8s3WUBu18hlioMvPuK7oy7WGl+TdQaQK5WkUtXtlzIQDIcJ5upNpX/4Fokb2uHb8Ub+rf3l3hEiQCKe58aXFlo6Ar5THnA780SDrJX6Y/OyzliHyYZhwTFaxMyFZt0qQN3ADuKAd+dfQNAQnxASULprf55DyPWGOO+vS/Px6+Vi0Rz+aX+QI8eB2ENg8y62L0gXDsCBsipIvj/ei5ooiND6qtmGuFTO25yqkYDrp+jvw4Gppv/PpU9iCIK9nIdDb/w417/xkbof0sFAzX7dDhUwO76Ymtm3SpX+SA/Cdfig2/U9GVuRDv++U3giH5J7exgAUCRAhC8B06oJyoqkuJMXtKhS5iEuJRGYjFRERfIKtvwiDr83P17vCbt9fLx+h2v5judYCMYE0VfcgsHd2/3YH5NBI8FV4jl+lj3rL9+S/x6bkxad4h/AM20Ejqn0PCO+bDh/+iccZ9FSl107tCkPLXiFedrVFBMG42smi9tNtgm9/Oqhd8Lsy/PAGQzl1abbEjRS38wK11LUCsXV8KuxLmVHL6m44ic4+EXoohLAr4jwXrdeAqRtlZW3gR8xF8fh1/+zTM0KZN0qmZoyPmhRLhjBNgbLdJyAsoUo5nwFvcqY2RQ0BFBiIYQvTe5Mxi9pyV7r8qD0YRucH608VxEbEkDfVuhSTru8Zw/CSZbpm6GNlmMk3wDjh2TS+BJ3O9qcvG/0r5LztaaLRpv6t4bSYHZDWYFGckSJSfGD+OCcNlyc5wo+XbGk69rSPawAypjMzUfPqGtBdzL1ZHoVTtzGmOCRjPTHsOW17LW0TuSv1DKzII3VA==
  template:
    metadata:
      creationTimestamp: null
      name: linkerd-trust-anchor
      namespace: linkerd
    type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  interval: 5m0s
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
  releaseName: linkerd
  targetNamespace: linkerd
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
    installNamespace: false
  valuesFrom:
  - kind: Secret
    name: linkerd-identity-issuer
    valuesKey: ca.crt
    targetPath: global.identityTrustAnchorsPEM