apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
  interval: 5m0s
  releaseName: csi-secrets-store
  targetNamespace: csi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-provider-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets-store-csi
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/vault-provider-csi
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: vault-provider-csi
  targetNamespace: csi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: key-vault-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: vault-provider-csi
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/key-vault-csi
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: key-vault-csi
  targetNamespace: csi