---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-init-scripts
data:
{{- with .Values.initdbScripts }}
{{ toYaml . | indent 2 }}
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{.Chart.Name}}'
  labels:
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{.Chart.Name}}
        image: 'postgres'
        env:
        {{- range $k, $v := .Values.envVars }}
          - name: {{ $k | upper }}
            value: {{ $v | quote }}
        {{- end }}
        command: ["/bin/bash", "-e", "/tmp/init-scripts/create_script.sh"]
        volumeMounts:
          - mountPath: "/tmp/init-scripts"
            readOnly: true
            name: init-scripts
      volumes:
        - name: init-scripts
          configMap:
            name: post-init-scripts
            defaultMode: 420
      initContainers:
        - name: wait-for-database
          image: jwilder/dockerize
          command: ['dockerize', '-timeout', '30s', '-wait', 'tcp://stolon-proxy.stolon:5432']