apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: stable
  interval: 5m0s
  releaseName: sealed-secrets
  targetNamespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-dependents
  namespace: flux-system
spec:
  dependsOn:
    -
      name: sealed-secrets
  chart:
    spec:
      chart: ./charts/sealed-secrets-dependents
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: sealed-secrets-dependents
  targetNamespace: flux-system