initdbScripts:
  create_script.sh: |
    #!/bin/bash

    # Loop over sql files and execute them via psql
    for component in $(echo $COMPONENTS | sed "s/|/ /g"); do
      PASSWORD="${component}_PASSWORD"
      psql --host ${HOST} -U ${USERNAME} -d postgres -c "CREATE DATABASE ${component,,};"
      psql --host ${HOST} -U ${USERNAME} -d ${component,,} -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
      psql --host ${HOST} -U ${USERNAME} -d ${component,,} -c 'CREATE EXTENSION IF NOT EXISTS "pg_trgm";'
      psql --host ${HOST} -U ${USERNAME} -d postgres -c "CREATE USER ${component} WITH ENCRYPTED PASSWORD '${!PASSWORD}';"
      psql --host ${HOST} -U ${USERNAME} -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE ${component} TO ${component};"
    done
  init_execution_tracker.sql: |

envVars:
# Pass via HelmRelease ValueFrom