apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  alertmanager.yml: |-
  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: {{ .Values.groupWait}}
    group_interval: {{ .Values.groupInterval}}
    repeat_interval: {{ .Values.repeatInterval}}
    receiver: {{ .Values.receiver }}
    routes:
    - match:
        service: {{ .Values.service }}
        receiver: {{ .Values.receiver }}
        severity: major
  inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  receivers:
  - name: {{ .Values.receiver | quote}}
    webhook_configs:
      - url: {{ .Values.serviceEndpoint }}
        send_resolved: true