---
# tasks file for gotk
- name: Download and install GitOps Toolkit
  become: yes
  shell: curl -s https://toolkit.fluxcd.io/install.sh | sudo bash

- name: Check prerequisites
  shell: flux check --pre

- name: Bootstrap flux
  shell: >
    GITHUB_TOKEN={{ github_token }}
    flux bootstrap github
    --owner={{ github_user }}
    --repository={{ github_repo }}
    --branch=main
    --path=minikube
    --personal