{{- template "common.deployment" (list .Values.deployment "execution-watcher-consumer.deployment") -}}
{{- define "execution-watcher-consumer.deployment" -}}
spec:
  replicas: {{ .replicas }}
  template:
    spec:
      imagePullSecrets: 
      - name: {{ .imagePullSecret }}
      containers:
      - {{ template "common.container" (list . "execution-watcher-consumer.container") }}
{{- end -}}
{{- define "execution-watcher-consumer.container" -}}
env:
{{- range $k, $v := .env }}
- {{ template "common.envvar.secret" (list $v.name $v.secretName $v.secretField )}}
{{- end }}
{{- end -}}