apiVersion: v2
name: gateway-consumer
description: A Helm chart for deploying gateway-consumer
type: application
version: 0.0.2
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.0.2
  repository: file://../common
