- name: Install linkerd2 edge
  shell: curl -sL https://run.linkerd.io/install-edge | sh

- name: Test for source
  shell: grep -c ".linkerd2/bin" /home/{{ username }}/.bashrc || true
  register: test_source

- name: Add linkerd2 to path
  lineinfile:
    dest: /home/{{ username }}/.bashrc
    line: "export PATH=$PATH:/home/{{ username }}/.linkerd2/bin"
    owner: "{{ username }}"
  when: test_source.stdout == "0"