---
- name: Ensure prereqs are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python3
    - python3-pip

- name: Install bottle python package
  pip:
    name: docker
    executable: pip3

    