---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-generator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/secrets-generator
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: secrets-generator