---
apiVersion: helm.toolkit.fluxcd.io/v2beta1 
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: codecentric
  interval: 1h0m0s
  releaseName: keycloak
  targetNamespace: authzn
  values:
    keycloak:
      persistence:
        deployPostgres: true
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: ambassador
        linkerd.io/inject: enabled
        meta.helm.sh/release-namespace: authzn
      enabled: true