FROM scratch

COPY gateway-api /gateway-api

# ADD https://raw.githubusercontent.com/ConnectCorp/docker-scratch-ssl/master/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt


CMD ["/gateway-api"]
