{{- template "common.deployment" (list .Values.deployment "app.deployment") -}}
{{- define "app.deployment" -}}
spec:
  replicas: {{ .replicas }}
  template:
    spec:
      imagePullSecrets: 
      - name: {{ .imagePullSecret }}
{{- end -}}