apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets-generator
      namespace: flux-system
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: mongodb
  targetNamespace: mongodb
  valuesFrom:
  - kind: Secret
    name: mongodb-superuser
    valuesKey: admin_password
    targetPath: auth.rootPassword