deployment:

  name: warden
  replicas: 3
  ports:
  - containerPort: 1080
    name: http
  env:
  - name: WARDEN_DB_PASSWORD
    secretName: warden-psql-creds
    secretField: password
  - name: WARDEN_SESSION_SIGNING_KEY
    secretName: session-signing-key
    secretField: session_signing_key
  - name: WARDEN_GITHUB_CLIENT_SECRET
    secretName: github-oauth
    secretField: client_secret
  - name: WARDEN_GITHUB_CLIENT_ID
    secretName: github-oauth
    secretField: client_id
  - name: WARDEN_CALLBACK_URL
    secretName: github-oauth
    secretField: callback_url
  image:
    repository: registry.eywa.rekfuki.dev/warden
    tag: latest
    pullPolicy: Always
  imagePullSecret: image-pull-secret

service:

  name: warden
  ports:
  - name: http
    protocol: TCP
    port: 1080
    targetPort: 1080