{{- define "service" -}}
apiVersion: v1
kind: Service 
metadata:
  namespace: {{ .namespace }}
  name: {{ .data.name }}
  labels:
  {{- include "labels" .data.labels | nindent 4 }}
spec:
  ports: 
  {{- include "ports" .data.spec.ports | nindent 4 }}
  selector:
  {{- include "labels" .data.selector | nindent 4 }}
  minAvailable: {{ .data.minAvailable }}
  publishNotReadyAddresses: {{ .data.publishNotReadyAddresses | default false}}
  clusterIP: {{ .data.clusterIP }}
{{- end -}}