{{- define "statefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .namespace }}
  name: {{ .data.name }}
spec:
  serviceName: {{ .data.name }}
  replicas:  {{ .data.replicas }}
  updateStrategy:
    type: {{ .data.updateStrategy }}
  selector:
    matchLabels:
  {{- include "labels" .data.labels | indent 6}}
  {{- if .data.spec.container.volumeClaimsTemplates }}
  volumeClaimTemplates:
  {{- range .data.spec.container.volumeClaimsTemplates }}
  - metadata:
      namespace: {{ .namespace }}
      name: {{ .name }}
    spec:
      accessModes:
        {{- range .accessModes }}
        - {{ . }}
        {{- end }}
      resources:
        requests:
          storage: {{ .requestsStorage}}
  {{- end }}
  {{- end}}
  template:
    metadata:
      namespace: {{ .namespace }}
      labels:
      {{- include "labels" .data.labels | indent 8}}
    spec:
      containers:
      - name: {{ .data.name }}
        image: {{ .data.spec.container.image}}
        imagePullPolicy: {{ .data.spec.container.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .data.spec.container.requestsCPU }}
            memory: {{ .data.spec.container.requestsMemory }}
        ports:
        {{- include "ports" .data.spec.container.ports | indent 10 }}
        livenessProbe:
        {{- include "probe" .data.spec.container.livenessProbe | indent 10}}
        readinessProbe:
        {{- include "probe" .data.spec.container.readinessProbe | indent 10}}
        command:
        {{- range .data.spec.container.command }}
          - {{ . }}
        {{- end}}
        {{- if .data.spec.container.volumeMounts }}
        volumeMounts:
        {{- range .data.spec.container.volumeMounts}}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
        {{- end }}
        {{- end }}
        {{- if .data.spec.container.env }}
        env:
        {{- range .data.spec.container.env }}
        - name: {{ .name }}
          valueFrom:
            fieldRef:
              fieldPath: {{ .fieldPath }}
        {{- end }}
        {{- end}}
        {{- if .data.spec.container.volumes }}
        volumes:
        {{- range .data.spec.container.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaimName }}
        {{- end }}
        {{- end}}
      terminationGracePeriodSeconds: {{ .data.spec.terminationGracePeriodSeconds }}
{{- end -}}