---
- name: Ensure prereqs are installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ntp
    - curl
    - gnupg-agent
    - software-properties-common

- name: Docker repo key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Work out the version
  command: lsb_release -sc
  register: version

- name: Docker repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ version.stdout }} stable
    update_cache: yes
    state: present

- name: Install Docker
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    force: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Add user {{ username }} to docker group"
  become: yes
  user:
    name: "{{ username }}"
    groups: [docker]
    append: yes
