---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: flux-system
spec:
  dependsOn:
    - name: key-vault-csi
      namespace: flux-system
    - name: init-stolon
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/registry
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: registry
  targetNamespace: faas-system