apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-dependents
  namespace: flux-system
spec:
  dependsOn:
    -
      name: cert-manager
  chart:
    spec:
      chart: ./charts/cert-manager-dependents
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: cert-manager-dependents
  targetNamespace: cert-manager