{{ range .Values.secrets  }}

{{- $values := dict }}
{{- range .fields }}
{{- $_ := set $values .name (.value | default (randAlphaNum 40) | b64enc) }}
{{- end}}

{{- $root := . }}

{{- range .namespaces }}
{{- $values = merge (lookup "v1" "Secret" . $root.name).data $values }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.name }}
  namespace: {{ . }}
data:
{{- range $k, $v := $values }}
{{- $k | nindent 4}}: {{ $v }}
{{- end }}
{{- end }}
{{ end }}