{{ range .Values.secrets  }}
{{- $root := .}}
{{- $pwd := randAlphaNum 40 }}
{{- range .namespaces }}
{{- if not (lookup "v1" "Secret" . $root.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.name }}
  namespace: {{ . }}
data:
{{- range $root.fields }}
{{- if .value }}
{{- .name | nindent 4}}: {{.value | b64enc }}
{{- else if .generate }}
{{- .name | nindent 4}}: {{ $pwd | b64enc }}
{{ end }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}