secrets:
# BEGIN STOLON
- name: stolon-replication
  namespaces:
  - stolon
  - flux-system
  fields:
  - name: pg_repl_username
    value: repl-admin
  - name: pg_repl_password
    generate: true

- name: stolon-superuser
  namespaces: 
  - stolon
  - flux-system
  fields:
  - name: pg_su_username
    value: admin
  - name: pg_su_password
    generate: true

# EXECUTION TRACKER
- name: execution-tracker-psql-creds
  namespaces:
  - faas-system
  - flux-system
  fields:
  - name: password
    generate: true

# WARDEN
- name: warden-psql-creds
  namespaces:
  - faas-system
  - flux-system
  fields:
  - name: password
    generate: true

# TEST
- name: test-psql-creds
  namespaces:
  - faas-system
  - flux-system
  fields:
  - name: password
    generate: true
