apiVersion: v2
name: vault-provider-csi
description: A Helm chart for deployin kubernetes secrets csi vault provider
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: common
  version: 0.0.2
  repository: file://../common