{{- $vaultAddress := .Values.vaultAddress -}}
{{- $vaultRoleName := .Values.vaultRoleName -}}
{{- range $k, $v := .Values.loaders -}}
{{- $context := $v -}}
{{- range $v.namespaces }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ $context.name }}-vault-sync
  namespace: {{ . }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ $vaultAddress }}
    roleName: {{ $vaultRoleName }}
    vaultSkipVerify: "true"
    objects:  |
      array:
{{- range $context.secrets -}}
{{- $vaultPath := .vaultPath -}}
{{- range .fields }}
        - |
           objectPath: {{ $vaultPath }}
           objectName: {{ .vaultKey }}
           objectVersion: ""
{{- end }}
{{- end }}
  secretObjects:
{{- range $context.secrets }}
  - secretName: {{ .kubeName }}
{{ toYaml (dict "labels" (default dict .labels)) | indent 4 }}
    type: {{ .kubeType }}
    data:
{{- range $k, $v := .fields }}
    - objectName: {{ $v.vaultKey }}
      key: {{ $v.kubeKey }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
