{{- range $k, $v := .Values.loaders -}}
{{- $context := $v -}}
{{- range $v.namespaces }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $context.name }}
  namespace: {{ . }}
  labels:
    app: {{ $context.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $context.name }}
  template:
    metadata:
      labels:
        app: {{ $context.name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: nginx
        name: secret-provider
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $context.name }}-vault-sync
{{- end -}}
{{- end -}}