{{- template "common.deployment" (list .Values.deployment "gateway-consumer.deployment") -}}
{{- define "gateway-consumer.deployment" -}}
spec:
  replicas: {{ .replicas }}
  template:
    spec:
      serviceAccount: {{ .serviceAccountName }}
      imagePullSecrets: 
      - name: {{ .imagePullSecret }}
{{- end -}}