---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: flux-system
spec:
  dependsOn:
    - name: key-vault-csi
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/app
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: app
  targetNamespace: frontend
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: swagger-ui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/swagger-ui
      sourceRef:
        kind: GitRepository
        name: eywa-charts
  interval: 5m0s
  releaseName: swagger-ui
  targetNamespace: frontend