---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: gotk-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.0.3
  interval: 5m
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true